#!/bin/bash

sd='/home/acemany/projects/github/My-msav'

cd $sd

git fetch
git pull


rm -rf ./steam 
mkdir steam

cp -r '/home/acemany/.steam/debian-installation/steamapps/common/Mindustry/saves/maps'         './steam/maps'
cp -r '/home/acemany/.steam/debian-installation/steamapps/common/Mindustry/saves/mods'         './steam/mods'
cp -r '/home/acemany/.steam/debian-installation/steamapps/common/Mindustry/saves/saves'        './steam/saves'
cp -r '/home/acemany/.steam/debian-installation/steamapps/common/Mindustry/saves/schematics'   './steam/schematics'
cp    '/home/acemany/.steam/debian-installation/steamapps/common/Mindustry/saves/settings.bin' './steam/settings.bin'


be_version=$(echo echo $(\ls /home/acemany/.local/share/Mindustry/be_builds) | cut -d. -f 1 | cut -d- -f 3)
echo "Current BE version is $be_version"

rm -rf "./bleeding-edge"
mkdir "bleeding-edge"

echo $be_version > ./bleeding-edge/version.txt
cp -r '/home/acemany/.local/share/Mindustry/maps'         './bleeding-edge/maps'
cp -r '/home/acemany/.local/share/Mindustry/mods'         './bleeding-edge/mods'
cp -r '/home/acemany/.local/share/Mindustry/saves'        './bleeding-edge/saves'
cp -r '/home/acemany/.local/share/Mindustry/schematics'   './bleeding-edge/schematics'
cp    '/home/acemany/.local/share/Mindustry/settings.bin' './bleeding-edge/settings.bin'


git add *

git commit -m "Auto upload from steam and BE-$be_version versions saves path"
# git push
