#!/bin/bash

sd='/home/acemany/projects/github/My-msav'

cd $sd

git fetch
git pull


rm -rf ./steam 
mkdir steam

cp -r '/home/acemany/.steam/debian-installation/steamapps/common/Mindustry/saves/maps'         './steam/maps'
cp -r '/home/acemany/.steam/debian-installation/steamapps/common/Mindustry/saves/mods'         './steam/mods'
cp -r '/home/acemany/.steam/debian-installation/steamapps/common/Mindustry/saves/saves'        './steam/saves'
cp -r '/home/acemany/.steam/debian-installation/steamapps/common/Mindustry/saves/schematics'   './steam/schematics'
cp    '/home/acemany/.steam/debian-installation/steamapps/common/Mindustry/saves/settings.bin' './steam/settings.bin'


git add *

git commit -m 'Auto upload from steam and be version saves path'
# git push
