#! /bin/python3

from requests import get as r_get
import click


@click.command()
@click.argument('prompt')
def main(prompt: str):
    """Shows you most populaar r34 for PROMPT"""
    lnk: str = f"https://api.rule34.xxx/autocomplete.php?q={prompt}"

    resp = r_get(lnk)

    code: int = resp.status_code
    click.echo(resp.text if code > 399 else '' + click.style(code, fg=("grey", "green", "yellow", "red", "bright_red")[code//100-1]))

    if not code < 400:
        return

    for tag in resp.json():
        tag_num = tag["label"].split(' ', maxsplit=1)
        click.echo(f'{click.style(tag_num[0], fg="green")}: {int(tag_num[1][1:-1]):,}')


if __name__ == "__main__":
    main()
